"""initial schema

Revision ID: 3218e9373ac3
Revises: 
Create Date: 2026-09-10 12:36:33.206659

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3218e9373ac3'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('email', sa.String(length=254), nullable=False, comment='Email'),
    sa.Column('password_hash', sa.String(length=255), nullable=False, comment='Хэш пароля'),
    sa.Column('first_name', sa.String(length=100), nullable=False, comment='Имя'),
    sa.Column('last_name', sa.String(length=100), nullable=False, comment='Фамилия'),
    sa.Column('role', sa.Enum('user', 'moderator', 'admin', name='user_role', native_enum=False, length=20), server_default='user', nullable=False, comment='Роль пользователя'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.PrimaryKeyConstraint('id', name='pk_users'),
    comment='Пользователи системы'
    )
    op.create_index('idx_users_email', 'users', ['email'], unique=True)
    op.create_index('idx_users_role', 'users', ['role'], unique=False)
    op.create_index('idx_users_role_created', 'users', ['role', 'created_at'], unique=False)
    op.create_table('events',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('title', sa.String(length=254), nullable=False, comment='Название мероприятия'),
    sa.Column('description', sa.Text(), nullable=True, comment='Описание мероприятия'),
    sa.Column('location', sa.String(length=255), nullable=False, comment='Местоположение'),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False, comment='Дата начала мероприятия'),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=False, comment='Дата окончания мероприятия'),
    sa.Column('capacity', sa.Integer(), nullable=False, comment='Количество человек'),
    sa.Column('owner_id', sa.Integer(), nullable=False, comment='Идентификатор организатора'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата создания'),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата обновления'),
    sa.CheckConstraint('capacity > 0', name='ck_events_capacity_positive'),
    sa.CheckConstraint('end_time > start_time', name='ck_events_end_time_after_start_time'),
    sa.ForeignKeyConstraint(['owner_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_events'),
    comment='Мероприятия, создаваемые пользователями'
    )
    op.create_index('idx_events_owner_id', 'events', ['owner_id'], unique=False)
    op.create_index('idx_events_owner_start', 'events', ['owner_id', 'start_time'], unique=False)
    op.create_index('idx_events_start_time', 'events', ['start_time'], unique=False)
    op.create_index('idx_events_time_range', 'events', ['start_time', 'end_time'], unique=False)
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False, comment='Идентификатор'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='Идентификатор пользователя'),
    sa.Column('jti', sa.String(length=36), nullable=False, comment='Уникальный идентификатор токена (JWT ID)'),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False, comment='Дата и время истечения срока действия токена'),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True, comment='Дата и время отзыва токена (пусто, если токен активен)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='Дата и время создания токена'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name='pk_refresh_tokens'),
    comment='Хранит refresh-токены пользователей для продления сессии'
    )
    op.create_index('idx_refresh_tokens_expires_at', 'refresh_tokens', ['expires_at'], unique=False)
    op.create_index('idx_refresh_tokens_jti', 'refresh_tokens', ['jti'], unique=True)
    op.create_index('idx_refresh_tokens_user_id', 'refresh_tokens', ['user_id'], unique=False)
    op.create_index('idx_refresh_tokens_user_revoked', 'refresh_tokens', ['user_id', 'revoked_at'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_refresh_tokens_user_revoked', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_user_id', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_jti', table_name='refresh_tokens')
    op.drop_index('idx_refresh_tokens_expires_at', table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_index('idx_events_time_range', table_name='events')
    op.drop_index('idx_events_start_time', table_name='events')
    op.drop_index('idx_events_owner_start', table_name='events')
    op.drop_index('idx_events_owner_id', table_name='events')
    op.drop_table('events')
    op.drop_index('idx_users_role_created', table_name='users')
    op.drop_index('idx_users_role', table_name='users')
    op.drop_index('idx_users_email', table_name='users')
    op.drop_table('users')
    # ### end Alembic commands ###
